//:doctitle:
:authors: B. H.
:revdate: 2018. dec. 11.
:lang: hu

ifndef::backend-pdf[:nofooter:]
:last-update-label!:

:note-hu:        fuzet
:rcod-en:        recoding
:rcod-hu-pdf-a4: downloads/atkodolas-a4.pdf
:rcod-hu-pdf-m:  downloads/atkodolas-m.pdf

ifndef::backend-pdf[:toc: macro]
:toc-title: Tartalom
:toc-levels: 3

= Az átkódolás

ifndef::backend-pdf[]
Letöltés: link:{rcod-hu-pdf-a4}[*pdf (A4)*], link:{rcod-hu-pdf-m}[pdf (mobil)]
endif::[]

ifndef::backend-pdf[toc::[]]

== Bevezető

Tisztelt olvasó, ön szerint mekkora erő vagy energia lehet az, amely kb. 15 perc alatt megváltoztathat egy embert? Mekkora erő lehet az, ami könnyedén megszabadít a rossz szokásoktól, ami megmutatja a helyes vágyakat? Mekkora erő lehet az, ami a lustaságot, a hanyagságot, a közömbösséget és a tehetetlenséget megszüntetheti bennünk, amely betegségeket képes gyógyítani, és amely néhány perc alatt úgy feltölt, hogy átalakító hatása hónapok, akár évek múltán is érződik? Mekkora energia lehet ez? És honnan származhat egy ekkora energia? Egyáltalán, ilyesmi létezik-e, létezhet-e a világon?

Ezekre a kérdésekre Ön csakis a saját tapasztalata révén kaphat választ. Semmiképpen sem másként. Ám tegyük fel, hogy mindez igaz, hogy valóban létezik egy erő, mely képes az embert jóvá, lelkiismeretessé, boldoggá stb. tenni.

Gondoljon csak bele! Ha valóban létezik egy ilyen energia, amely az előbb említett tulajdonságokat fel tudja ébreszteni bennünk és, ha ez elterjedne, ha egyre és egyre több ember részesülne benne, milyen lenne a világ? Milyen lenne a társadalom? Milyen lenne gyermekeink, unokáink jövője? Milyen lenne, ha az Ön vagy gyermekei főnöke, papja, lelkésze, tanárja, tanítója, orvosa valójában hivatásának élne, tiszta lelkületű, megértő, türelmes, szeretni tudó ember lenne? Milyen világban élnénk, ha mindenki valóban be tudná teljesíteni mély lelki vágyait, küldetését? Természetesen egy gyönyörű világban, egy olyan világban, melyet csak álmainkban tudtunk elképzelni és, amelyről eddig azt hittük, hogy megvalósíthatatlan.

Tudom, e sorokat olvasva a legtöbb ember fejében kétkedés, hitetlenség jelenik meg. Sokan magukban azt gondolják: ilyen erő nem létezhet, nem is létezik, itt, valami nem tiszta, itt valami trükk van: érdek, esetleg csalás.

Az előbbi részeket megismerve, nem csak Ön, hanem más ember is így reagált volna, de csak 2008. január 19.-ig. Ugyanis azon a napon valami csodálatos dolog történt, egy olyan dolog, mely által elkezdődött: az *ÁTALAKULÁS*!

Bizonyos, megbízható források szerint, ha nem fogunk megváltozni, a jövőben társadalmunk nehéz helyzetbe fog kerülni. Amikor az ember biztosan tudja, hogy nehézségek várnak rá, akkor megpróbálja elkerülni azokat. Társadalmunk egyre nehezebb gondokkal küszködik. És ezek a problémák minden előrejelzés szerint csak súlyosbodni fognak. Ezért néhány barátommal együtt úgy gondoltuk, hogy képességeinkhez mérten tenni fogunk ellene. Mi körülbelül már egy éve figyelmeztetve voltunk arra vonatkozóan, hogy sok probléma várhat ránk, ám akkor hiába mondtuk ezt és hiába kínáltuk fel az egyik hatékony megoldási lehetőséget. Akkor kevesen hittek nekünk és kevesen hitték el, hogy a továbbiakban leírt átkódolás gyógyír lehet, egy eszköz a társadalom újjáépítésében. 2008. januárjában minden kétséget kizáróan megtudtuk (hogy honnan az a későbbiekben kiderül), hogy egyre több és több szenvedés vár a társadalmunkra.

Ezt látva nagyon erős vágy ébredt fel bennünk, hogy, ha csak egy mód van rá, akkor állíthassuk le a társadalomra váró nehézségeket vagy legalábbis mérsékeljük azokat.
Ez meg is történt. Ahhoz, hogy megértsük miképpen, elmondanék néhány dolgot a világban működő szellemi törvényekről.

Először is beszélnem kell Istenről. Tudom, hogy általában háromféle ember van. Van az ateista ember, aki egyáltalán nem hisz semmilyen szellemi erőben, törvényben és -- főleg - nem hisz Istenben. Van egy másik típusú ember, aki elfogadja egy felsőrendű hatalom létét, de nem ért egyet a vallásokban fellelhető Isten-képpel. És van a vallásos ember, aki az egyházak, szent könyvek által tanított Istent fogadja el valóságként. Természetesen e kategóriákon belül számos - részleteiben eltérő - altípus létezik, hiszen ahány ember van, annyiféle tudatszint is. Nekem feladatom ebben az anyagban mindhárom fő típushoz szólni, ezért, megkérem Önöket, hogy a továbbiakban leírt részekben legyenek toleránsak a másik két típushoz, melybe Önök nem tartoznak, illetve, hogy igyekezzenek a szöveget a saját világuknak megfelelően értelmezni.

Véleményem szerint, aki nem hisz valamilyen formában egy tökéletes, mindent átfogó és irányító erőben, amit a hívők Istennek neveznek, az vagy nem gondolkodott még el mélyebben a világ dolgairól, vagy nem ismeri a tudományokat behatóbban, vagy egész egyszerűen még nem eléggé intelligens és ezáltal nem tudja megérezni a valóságot. Semmi probléma. Ma a tudomány a kvantumfizika segítségével már bebizonyította egy mindent átfogó és mindent irányító tudat (Isten) létét.

Több tudós, ezzel a témával kapcsolatosan megalkotta a világ egyik legcsodálatosabb dokumentum filmjét, mely segítségével, több szempontból is bebizonyította Isten jelenlétét. Ennek a filmnek a címe: "What The Bleep! do We Know?", vagyis: "Mi a csudát tudunk a világról?" A film alapján már egy könyv is létrejött. Azoknak az embereknek, akik nem hisznek Istenben, azt tanácsolom, hogy szerezzék meg ezt a filmet és nézzék meg figyelmesen. Biztos vagyok, hogy ez a film Önöknek is meg fogja mutatni, hogy miképpen látja a tudomány Isten jelenlétét a világban. Azoknak pedig, akik jelenleg már vallásosak és meg akarják nézni ezt a filmet, azt tanácsolom, hogy legyenek nagyon nyitottak, ne botránkozzanak meg, hiszen a tudomány másként közelíti meg az igazságokat, mint a vallás. Ugyanakkor nekik még azt is tanácsolom, hogy ne feledjék el Jézus mondását: _"Én Atyámban vagyok, ti pedig Énbennem, és Én tibennetek."_ (János 14/20) A film ugyanis ezt a témát taglalja, csak tudományos szempontból.

A Világegyetemet (így bennünket is) átölelő és irányító tudatot sokféleképpen el lehet nevezni. Én a továbbiakban a köztudatban létrejött "Isten" fogalmával fogom említeni. Hogy ez alatt mit értek, azt részben tudni fogják a filmből, ám egy bizonyos mértékben bemutatnám jómagam is, hogy tudományos szempontból mit is értek az Isten és a vele történő kommunikáció fogalma alatt. Természetesen a hívőknek már sok tapasztalatuk lehet Istenről, ám mégis nekik is ajánlom, hogy más megközelítésből is megismerjék Őt.

Az előbbi részben elmondtam, hogy néhány barátommal egyetemben le akarunk állítani bizonyos, a társadalmat súlyosan érintő problémákat. A továbbiakban be szeretném mutatni, hogy miként lehetséges ez.

A bibliában írva van: _"Bármit kértek majd nevemben az Atyától, megadja nektek"_, vagy: _"Kérjetek és kaptok"_ (János 16/24) stb. Ha valaki tiszta szívből, őszintén és mélyen fordul Istenhez, könyörögve kéri a kiengesztelést, megkapja. A hívők tudják és sokan tapasztalták már, hogy az igazi, lelki mélységből származó kérések igenis bekövetkeznek. Erre számos példa található a történelemben.

Nézzük meg, hogy ezek a kérések milyen formában következhetnek be.

Agyunk működése egy igen komplex, bonyolult folyamat. A mindennapi gondolkodásunk bizonyos frekvencia értékeken belül történik. Ez a 14-30 Hz (a hullámok rezgési frekvenciáját a Hertz mértékegységgel mérik, ami azt jelenti, hogy ciklus/szekundum) frekvencia számon történik. A tudósok ezt a szintet beta (β) szintnek nevezték el. A szellemi nyugalom állapotában, agyunk egy mélyebb frekvencián, a 8-13 Hz rezgésszámon fejti ki tevékenységét. Már ezen a szinten fokozódnak lehetőségeink, elképzeléseink valóságosabbakká válnak, tudatunk mélyebb szintre kerül, intuíciónk megnövekszik, jobban megérezzük, hogy fontosabb döntéseinkben mi lenne a helyes vagy helytelen. Ezt a szintet a tudósok az alfa (α) szintnek nevezik.

Természetesen létezik egy ennél is mélyebb tudatszint a theta (θ), mely a 4-7 Hz frekvencián működik. Itt már alig van a hétköznapi tudatszintnek megfelelő gondolatunk, mindent egy igen mély nézőpontból látunk. A thetánál is mélyebb tudatszintet (1-3 Hz frekvencia) deltának (δ) nevezik a tudósok. Ugyanakkor megállapították, hogy a delta szinten belül van egy mélyebb szint is, amikor úgynevezett rendszertelen hullámok dominálnak. Ez valójában egy transz állapot, ahol nagyon mély állapotba kerülünk és olyan dolgokat vagyunk képesek megérteni, megérezni, melyeket a felsőbb szinteken nem lennénk. A keresztények ezt az állapotot elragadtatásnak nevezik, az ősi népek sámánjai pedig révülésnek. Tény, hogy ezen a szinten képességeink megnövekednek, tisztán megértünk univerzális törvényeket, a problémákat és a megoldásokat is képesek leszünk érzékelni. Ezen a szinten tudatunk képességei közel végtelenek, egy hatalmas, határtalan "mindentudással" tudjuk felvenni a kapcsolatot. Más szóval, ezen a szinten nagymértékben megszűnik a személyiségünk és egybeolvadunk a mindenkiben és mindenben ott rejlő tudattal, magával *"A TUDATTAL"*, amiből minden életforma létrejött (így mi is). Ezen a szinten, amennyiben megmaradunk öntudatunknál (kapcsolatunk fennmarad a β szintű tudatunkkal), az érzékelésen keresztül olyan dolgokra kapunk magyarázatokat, válaszokat vagy megoldásokat, lehetőségeket, melyek a hétköznapi tudatunk szempontjából felbecsülhetetlen értékkel bírnak és csodának számítanak. Ezen a szinten a hétköznapi tudatunk állapotokat, mély érzéseket érzékel, melyet a β szintnek megfelelően az agyunk "szavakként" értelemez. Más szavakkal: a delta legmélyebb szintjén olyan mély tudatállapotba kerülünk, ahol minden problémának a megoldását megtalálhatjuk, ahol a mindentudás világával vehetjük fel a kapcsolatot és ahol bármilyen kérdésünk aktivál egy annak megfelelő választ (állapot formájában), ezt pedig a β tudatunk "szavakként" érzékeli. Valójában ezt a folyamatot nevezzük "Istennel való kommunikációnak". (Természetesen ez a bemutatás nagyon egyszerű és rövid, a valóságban sokkal több folyamat történik, pl.: a théta szinten érzékelhető egy nagyfokú szeretet stb.).

Ahhoz, hogy valaki tudatosan a delta mély szintjeire kerüljön, egy magasfokú lelki tisztasággal és őszinteséggel kell rendelkezzen, teljes szívéből kell akarja, hogy kapcsolatba kerüljön a mindentudás világával (más szavakkal nagyon kell vágyjon arra, hogy kommunikáljon Istennel), vagy pedig végtelenül őszintén kell akarjon segíteni az emberiségen vagy valaki máson.

Létezik egy univerzális törvény, mely megmutatja az igazi siker titkát.

E törvény szerint, ha csak egy célunk van, vagyis valamikor a jövőben el akarunk majd érni valamit, akkor tulajdonképpen rezonálunk azzal a ténnyel, hogy a kitűzött célunk jelenleg még nincsen meg, vagyis (tudat alatt) folyamatosan gátoljuk magunkat a cél elérésében. (Hiszen tudat alatt mindig az van a fejünkben, hogy a célunk még nincs megvalósulva.) Például: ha valaki egészséges akar lenni és ennek érdekében naponta ügyel arra, hogy hogyan táplálkozik, alszik stb., akkor valóban tesz lépéseket az egészség fele, de ugyanakkor naponta rezonál azzal a ténnyel is, hogy még nem egészséges. Márpedig ez a tény tudat alatt komoly hatással jár, hiszen ha az illető egészséges lenne, akkor nem lenne célja ennek elérése. Gondolom, láttak már sok olyan embert, akik naponta sokat tesznek azért, hogy felépítsenek egy egészséges testet. Erről sokat is beszélnek, ám mégis folyton kisebb-nagyobb egészségügyi problémájuk van. Akkor mi lenne az igazi megoldás? Elsősorban az előbbi példát figyelembe véve, tudatosítanunk kellene, hogy testünk eredendően egészséges, így annak csak a fenntartására, helyreállítására kellene koncentrálnunk, nem pedig az elérésére. Ám mégis van egy még ennél is jobb megoldás: az igazi siker titka. Célunkat nem céllá, hanem feltétellé, szükségszerűséggé kellene tennünk. Tovább fejtegetve a példánkat, mindaddig, amíg célunk az egészség elérése, addig fennállhat annak esélye, hogy csak közelíteni fogjuk célunkat, de teljesen nem fogjuk tudni elérni azt. Amennyiben viszont szükségszerű egészségesnek lennünk, akkor igenis el fogjuk érni. Például, ha csak egészségesek akarunk lenni, akkor bizonyos lépéseket fogunk tenni ennek érdekében, ám, ha meg akarjuk nyerni a jövő évben esedékes országos maratoni versenyt, akkor, feltétel, szükségszerűség az, hogy egészségesek legyünk és ebben az esetben egészen másképp fogunk gondolkodni és cselekedni. Ebben az esetben olyan jellegű edzéseket és életformát fogunk kialakítani, mely megköveteli a kiválóan egészséges testet (és amennyiben azelőtt betegek is voltunk, nagyon hamar képesek leszünk meggyógyulni), hiszen máskülönben nem tudnánk a maratoni versenyen nyerni. Még egy fontos tényező: ebben az esetben fel sem merül bennünk, még tudat alatt sem, hogy nem érjük el az egészséges testet, hiszen ez - az eredendő célunkhoz képest - egy feltétel. Nem lesz meg bennünk a visszafordulás lehetősége.

Amikor valakiben egy bizonyos cél esetén nincs meg tudat alatt a visszafordulás lehetősége, akkor valóban el tudja érni kitűzött célját! Akkor az illető olyan hatalmas univerzális energiákkal veszi fel a kapcsolatot, melyek jóval túllépik az emberi elme korlátolt világát és melyeknek segítségével az első látásra lehetetlennek tűnő célok is könnyedén megvalósulhatnak. Az ilyen esetekben felvesszük a kapcsolatot a legmélyebb tudat alatti világokkal, melyek már azonosak az Univerzumot felépítő szellemi erőkkel - vallásosok, úgy is mondhatják, hogy az Isteni Akarattal - és így céljaink megvalósulnak. Amikor az ember ilyen hatalmas erőkkel rendelkezik, akkor teljesen biztos abban, hogy számára a lehetetlen könnyen lehetségessé tud válni, bármiről legyen is szó. Ez az igazi siker titka. A szentek ilyen mély szinten tudtak kérni, éppen ezért kéréseik teljesültek, még olyan esetekben is, amikor erre hétköznapi szempontból nem volt reális lehetőség. Az ilyen megvalósulásokat hívja a keresztény világ csodának. Igazi szépsége e törvény megismerésének az, hogy tudatosításával és alkalmazásával nemcsak a szentek, hanem mi, hétköznapi emberek is képesek leszünk bármilyen nemes, igazi cél elérésére, a siker megtapasztalására!

{empty}2008. január 19.-én úgy éreztük, hogy most már feltétel és szükségszerűség valamit tennünk arra vonatkozóan, hogy amennyiben társadalmunk nem változik meg, nem tudatosul, megakadályozzuk azokat a nehézségeket, melyek be kellene következzenek és szebbé, jobbá tehessük számos máris szenvedő, beteg ember életét. Kérésünk az előbb leírt módon feltétel volt, tehát fel sem merült, hogy nem kapunk valamilyen megoldást ezekre a problémákra. Istenhez fohászkodtunk (gondolom, most már érthető, hogy miképpen történt ez meg). Kérésünk hihetetlen intenzív volt, ugyanis mi tudtuk, hogy az elkövetkezendő időszak sok ember számára borzalmas lehet. Isten valóban megmutatta, hogy amennyiben társadalmunk nem lesz hajlandó visszatérni az eredeti, a minden ember lelkében, így bennünk is mélyen érezhető igazságokhoz, vagyis az eredeti Isteni Akarathoz, akkor tényleg szükségszerű több katasztrófa, nehézség vagy akár végső estben egy nagyobb méretű háború kirobbanása, mely ekképpen elvezethet egy tisztuláshoz. Természetesen Isten kihangsúlyozta, hogy Neki nem célja és soha nem is volt az, hogy szenvedés vagy háború legyen a Földön. Ezek valójában az emberi tisztátalanság következményei, tehát nem az Ő Eredeti Akarata, hanem a szükségszerűség következményei, melyekkel Ő is egyet kell értsen. Isten azt is megmutatta, hogy Ő mindig is mindent megtett ezek elkerülése érdekében, ám, ha az emberiség a számtalan figyelmeztetés és a rendkívüli szeretet ellenére sem hajlandó megváltozni, akkor önmagát súlyos lelki, majd pedig fizikai válságba sodorja. Ez ellen pedig Maga Isten sem tehet, semmit, hiszen az Univerzum törvényei kimondják, hogy *a rossz* hosszú távon sohasem győzhet és meg kell értse tettei súlyát, márpedig ez csakis a tettei következményeinek megtapasztalásával vagy a szeretet megismerésével lehetséges. Ugyanis Isten, ha a megérdemelt következményeket mindig feloldaná, akkor *a rossz* a végtelenségig elharapózna és nem tudná felismerni tetteinek ártalmas voltát, *a jó* pedig nem tudná érvényesíteni erejét. Isten azt is megmutatta, hogy jelenleg az emberiség ismét egy mély lelki válságba sodródott, ahol hatalmas szereppel bír a negatív gondolkodás, a tehetetlenség, a lustaság, az erkölcstelenség és, ahol az igazi értékek elvesztették érvényességüket.

Ez az állapot már hosszú ideje tarthatatlan és amennyiben az emberiség nem fog visszatérni a szívében található igazságokhoz vagyis az Isteni Akarathoz, akkor, ismét komoly katasztrófák és nehézségek fognak bekövetkezni. Jelenleg a Föld lakossága két dolog közt választhat: vagy elviseli rossz tettei súlyos következményeit, vagy a szeretet, a lelki fejlődés fele fordul.

Ezeket látva megtudtuk, hogy az elkövetkezendő időszak sok ember számára borzalmas lehet. Megtudtuk, hogy élet-halál kérdése megoldani ezt a problémát. És azt mondtuk: nem érdekel minket az, hogy milyen áldozat árán, de, ha egy mód van rá, könyörögve kérjük a Világegyetemet irányító Tudatot, Istent, hogy adja meg a változás és változtatás lehetőségét! Tudtuk, hogy Ő bármire képes és ha akarja, megmutathatja a kivezető utat. Ezért a lehető legintenzívebben könyörögve, gyakorlatilag a könyörgéssel azonosulva, már-már a megoldást követelve oly mértékben fordultunk e kérésünkkel Istenhez, hogy valósággal remegett körülöttünk a levegő. Hosszú idő telt el így és semmilyen válasz nem érkezett. Ám mi egyre intenzívebben könyörögtünk a Kegyelemért. Ekkor nagyon lassan egy finom energia kezdett felülről lefele a testünkbe szállni, majd egyre intenzívebb lett. Szólni sem tudtunk a szentség és az Isten jelenlétének erőteljes érzékelése miatt. Körülbelül negyed órát-húsz percet tartott az energia alászállása. Miután vége lett, Isten azt mondta (az elején leírt módon), hogy ez az energia minden embert vissza tud csatolni az Eredeti Isteni Akarathoz. Isten ezt az energiát átkódolásnak nevezte el, mivel ez az energia átkódol minden embert az egoizmusból a valóságra, a tehetetlenségből az Isteni Akarat beteljesülésére. Utána pedig azt mondta, hogy jobb kezünk segítségével, mindenki, aki megkapta ezt az energiát, tovább tudja adni bárki másnak. Azt is mondta, hogy ad még egy esélyt az emberiségnek, ideiglenesen elhalaszt bizonyos katasztrófákat és amennyiben az átkódolást elterjesztjük a Föld lakosságának legalább háromnegyedénél, akkor véglegesen meg tudunk szabadulni minden nehézségtől, mely egyébként be kellene következzen. Ugyanakkor biztosított arról is, hogy valójában Ő akarta - szeretete által - az átkódolás létrejöttét, mi a kérésünk következtében csak megvalósítottuk az Ő eredeti szándékát. Azt is mondta, hogy ne féljünk, mert az Ő akarata az átkódolás elterjedése a Földön, így, ha az emberiség is akarja, bekövetkezhet az átalakulás. Azt is mondta, hogy azok akik meg fogják kapni az átkódolást, tulajdonképpen szabad akaratukból elkötelezik magukat arra, hogy Ő (Isten) átalakítsa lényüket és fokozatosan elvezesse őket a valódi boldogsághoz, a szeretethez, az Eredeti Isteni Terv megvalósulásához. Ha ez bekövetkezik, akkor tulajdonképpen Ő minden szinten át tudná venni az emberiség irányítását, ami egy csodálatos élethez vezethetné el a mai társadalmat.

Egyszóval Isten, végtelen szeretete által, 2008. Január 19-én este ismét adott egy esélyt az emberiségnek. Ugyanakkor azt is tudjuk, hogy ezeket a dolgokat a tavaly még sokan nem hitték el. Ám az azóta kirobbant gazdasági válság meg egyéb olyan tervek, melyeknek puszta gondolata is borzalommal tölti el az épeszű embert, egyre inkább arra mutatnak rá, hogy Isten ismét idejében figyelmeztetett bennünket (akárcsak a történelemben számtalanszor) és újra megadta a megoldás eszközét. A többi rajtunk múlik. Az átkódolás segítségével Isten megint adott egy új lehetőséget, mely által - ha akarja - az átlagember is megtisztulhat és élete új irányba fordulhat a jóság jegyében. (Annyit azért még el kell mondanom, hogy a bölcseknek, szenteknek Isten egyéb eszközöket is adott az átkódoláson kívül az emberiség megmentésére, melyeket viszont csak kevesen használhatnak és érthetnek meg.)

== Mi is valójában az átkódolás?

Isten ereje végtelen. Akarata bármire képes. Istennek hatalmában áll Galaxisokat teremteni, világokat létrehozni vagy megszüntetni. Ne feledjük el, hogy a tökéletesen működő Világegyetem Teremtőjéről beszélünk. Bármelyik tudományágat figyeljük meg, tökéletesen felépülő és működő rendszereket találunk benne. Tehát egyértelmű, hogy Isten felépített egy végtelen és tökéletes világot. Persze, sok ember ilyenkor megkérdezi, hogy, ha ennyire tökéletes a világ, akkor mégis miért van szegénység, háború, szenvedés? A kérdés jogos, a válasz pedig lényegében egyszerű. Azért, mert Isten a végtelen szeretete révén szabad akaratot adott nekünk, mi pedig ez által eltávolodtunk az Eredeti Isteni Tervtől és magunkra vontuk a múltbéli és jelenlegi hibáink következményeit. Más szavakkal: mivel mi, emberek, alkotni tudunk jót is, rosszat is, amennyiben nem figyeljük meg a mélyebb tudatunkban élő vágyainkat és a felszínes vágyaink szerint döntünk, természetes, hogy ez idővel számos problémát fog okozni. Ám mégis, pontosan azért, mert Isten tökéletes és szeretetében végtelen, egyénenként mindig is adott volt és most is mindenki számára adott a nehézségektől való megszabadulás lehetősége. Más szavakkal: ha felismerjük a bennünk levő mélységeket és azok szerint kezdünk el élni, akkor - idővel - minden rendbe jön. Ennek pedig csak egy feltétele van: megérteni és újból elkezdeni beteljesíteni az Isteni Akaratot. Vagyis a mély lelki vágyainkat. Az öt kontinens nagy szentjei és bölcsei minden időben azt állították és a jelenleg élők is azt mondják, hogy minden öröm, csoda vagy pedig baj és szenvedés - valahol mélyen - az Isten Végtelen Szeretetét tükrözi, tehát isteni szempontból értelme van. Természetesen ahhoz, hogy megértsük, hogy még a szenvedésnek is van értelme, bölcsnek kellene lennünk és meg kellene ismernünk az Univerzum lelki és szellemi törvényeit.

Mégis, még egyszer ki kell hangsúlyozni, hogy Isten nem akarja a szenvedést, ám időnként - azért, hogy ne fokozzuk még jobban magunkban *a rosszat* - szükséges a szenvedés árán lelkileg megtisztulnunk. Más szavakkal: ha felszínes életet élünk, akkor előbb-utóbb boldogtalanok lennénk, éppen ezért a szellemi törvényeknek megfelelően olyan helyzetekbe leszünk kényszerítve, melyek által kénytelenek leszünk elmélyülni. Ez azért következik be, mert valójában tudat alatt vágyunk rá! Természetesen, az az ember, aki szabad akaratából Isten fele fordul, lelkileg tiszta, valamint megfelelő intelligenciával rendelkezik, az nemhogy elkerüli a szenvedést, hanem egyenesen boldog életet tud élni! A valóság az, hogy minden ember, ha követné az Isteni Akaratot, akkor hihetetlen boldogság sorozatokban részesülne.

Mit gondol a Kedves Olvasó, hogy Isten, Aki felépítette az egész Világegyetemet, képes Önt megváltoztatni? A válasz logikus és egyértelmű. Akkor eddig miért nem tette meg? Akkor Ön miért nem boldog tökéletesen? Az igazság az, hogy azért, mert eddig Ön nem vágyott tiszta szívéből arra, hogy kövesse a mély vágyait, a szívét, ami nem egyéb, mint az Isteni Akarat. Mert Ön eddig nem szentelte életét annak a csodálatos feladatnak, amit ott mélyen a szívében érez és ami az Isteni Tervvel azonos. Lehet, hogy ezért Ön nem is annyira hibás, hiszen igazából eddig nem tapasztalta meg Isten jelenlétét (más szavakkal: az önben rejlő mélységeket), nem találkozott boldog emberrel, aki bebizonyíthatta volna, hogy a világ csodálatos. Lehet, hogy Ön eddig nem is tudott arról, hogy van kiút, van megoldás és hogy szép életet is lehet élni. Ám ennek ellenére a végtelen és mindenható Isten nem avatkozhatott bele az Ön életébe, mert tiszteletben tartotta az Ön szabad akaratát, vagyis azt, hogy Ön még nem óhajtja követni a tökéletes bölcsességet, szeretetet és boldogságot. Mélyek ezek az igazságok és döbbenetesek. Ugyanis rávilágítanak arra, hogy problémáinkból van kiút, bármikor abbahagyhatjuk a szenvedést, bármikor boldog és teljes életet élhetünk, bármikor ügyessé, sikeressé válhatunk, megtisztulhatunk, megtanulhatunk szeretni és szeretetben élni. Mindez csakis és kizárólag tőlünk függ. A kérdés valójában csak az, hogy meg akarjuk-e tenni a boldogsághoz vezető lépést, vagy nem? Eddig lehet, hogy azt gondoltuk, hogy a körülményeink, a nevelésünk, az anyagi helyzetünk, a munkahelyünk, a párkapcsolatunk, stb. a hibás azért, mert mi nem vagyunk boldogok. Ennek ellenére a valóság az, hogy Isten mindezeket a körülményeket meg tudná változtatni, neki ez semmiség, ám ehhez a beleegyezésünk szükséges. A beleegyezés pedig nem egyéb, mint a mély lelki vágyaink tudatosítása és annak a felvállalása, hogy mély érzéseinket követni fogjuk.

Ebben az esetben Isten beavatkozik az életünkbe, felkészít a számtalan és általunk jelenleg még elképzelhetetlen ajándék befogadására és fokozatosan elvezet a teljes, boldog élethez. Más szavakkal: ha tudatosítjuk a bennünk levő mélységeket és igyekszünk eszerint élni, akkor a mi életünkben is beindulhatnak azok az univerzális folyamatok, melyek alapján a világ működik, ami elvezet a boldogsághoz. Mindez azt jelenti, hogy életünk teljes megváltoztatása egy komoly döntésen alapszik, mely szerint megengedhetjük, hogy Isten átvegye életünk irányítását. Isten akarja, hogy boldogak legyünk, hiszen Ő szeret minket. Ha mi is akarjuk ezt, akkor nincs más dolgunk, mint igent mondanunk Istennek, hogy jöjjön és végtelen bölcsessége által, változtassa meg az életünket. Más szavakkal: ha mi tiszta szívből azt akarjuk, hogy az egoista vágyaink helyett a bennünk is jelenlevő tiszta, mély lelki vágyaink szerint éljünk, akkor igenis megtapasztaljuk, hogy érzéseink által vezetve leszünk. Nyugodtak lehetünk, ha ezt a lépést megtesszük, Isten meg fog nyilvánulni az életünkben és megváltoztat bennünket.

Az átkódolás Istennek egy eszköze, mely által elindíthatja bennünk a változások folyamatait. Természetesen nem feltétlenül szükséges az átkódolás segítségével fordulnunk Isten fele. Ezt a lépést megtehetjük egy egyszerű döntéssel is, melyben életünket őszintén Isten kezébe ajánljuk. Ám ennek ellenére az átkódolás egy hatásos eszköz, melynek segítségével az átalakulás kétségtelenül megtörténik. Az átkódolás egy olyan energia, ami által Isten beavatkozhat az életünkbe, megváltoztathatja a körülményeinket, ezáltal pedig megváltoztathatja érzéseinket, gondolatainkat, világnézetünket. Az átkódolás megváltoztatja testünket is, sőt, egyes vélemények szerint genetikai változásokat is előidéz, így súlyos betegségekből is felépülhetünk. Az átkódolás felszínre hozza a bennünk rejlő mély vágyakat és azt a valóságot, ami valójában vagyunk. Az átkódolás segítségével tulajdonképpen fokozatosan visszatérünk az Eredeti Isteni Akarathoz. Minden ember, aki saját szabad akaratából - tudván azt, hogy mit jelent az Isteni Akarat követése - ha meg akarja kapni az átkódolást, tulajdonképpen beleegyezik abba, hogy élete irányítását átvegye a Tökéletes Szeretet, vagyis az Isten.

Ahhoz, hogy a továbbiakban megértsük, mi is valójában az átkódolás, meg kell értenünk, hogy valójában mi is az Isteni Akarat? Valószínű, hogy eddig mind Istenről, mind pedig az Isteni Akaratról nem volt egy valóságos és helyes képünk.

Természetesen, a Végtelent teljes mértékben talán sohasem fogjuk megérteni, ám mégis, ha megismerünk Belőle néhány lényegi tulajdonságot, az csakis a javunkra válhat.

== Mi is valójában az Isteni Akarat?

Ahhoz, hogy erről egy képet alkothassunk, néhány dolgot meg kell értenünk Magáról az Istenről is. Jézus azt mondta: _"Én Atyámban vagyok, ti pedig Énbennem, és Én tibennetek."_ (János 14/20) És azt is mondta: _"Én és az Atya egy vagyunk"_ (János 10/30), máskor pedig azt mondta: _"Én az Atyához megyek"_ (János 14/12). Jézus szavaiban fellelhető egy kettősség. Hol az Istennel azonosult állapotáról beszél, hol pedig egy Tőle független Atyáról. Ez a rejtélyes kettősség bemutatja a mindannyiunkban fellelhető kettősséget is. Jézus egész élete példájával rólunk beszélt és értünk cselekedett. Így példája bemutatta, hogy nekünk is hogyan kell élnünk, gondolkodnunk, cselekednünk. Az emberben él egy kettősség, mely valójában csak az elme szempontjából kettősség. Igazából ugyanannak az Egyetlen Valóságnak a több nézőpontból való értékelése. Erre vonatkozóan nézzünk meg egy példát: ha valaki egy vonaton utazik és egy almát dob fel, akkor az függőlegesen mozog. Ám, ha ugyanezt a jelenetet egy - a vonaton kívül álló - személy az ablakon keresztül látja, akkor ő azt fogja észlelni, hogy az alma a vonat menetirányával ellentétes irányban egy ívet fog leírni. Ez természetes is, hiszen, ha a külső néző függőleges mozgást látna, akkor az alma annak a személynek a háta mögé kellene essen, aki feldobta azt, hiszen ez idő alatt a vonat jócskán haladt előre. Ez a példa bemutatja, hogy ugyanaz az Egy Valóság kétféleképpen is érzékelhető. (Ez az alapja a relativitás elméletének is.) Ugyanígy Isten is kettős formában érzékelhető bennünk. Nagyon mély állapotban a mi tudatunk eléri a mindenütt jelenlevő Isteni Tudatot és azonosul vele. Ekkor érezzük azt, hogy igazából önmagunkká válunk, hogy bármikor képesek vagyunk bármire stb. Ebben az állapotban igenis eggyé válunk az Isteni Tudattal, mert az egónk teljesen feloldódik a mindenütt jelenlevő Isteni Tudatban. Figyelem: nem Istennel válunk eggyé, hanem az Isteni Tudattal! Más esetben pedig Istenhez fohászkodunk, hogy segítsen valamiben. Tulajdonképpen ilyenkor a mindennapi tudatszintünkkel a bennünk is létező Teljességhez fordulunk, mely bizonyos képességek felébresztésével, illetve a környezet átalakítása segítségével képes kéréseinket teljesíteni. Nos, ez a két folyamat látszólag két különböző dolognak tűnik, ám valójában ez a két tudatállapot ugyanannak az Egy Valóságnak a különböző szintű érzékelése. Külön-külön nem lehetnek teljesek, hiszen hiába vagyunk nagyon mély, az Isteni Tudat állapotában, ha nem fejezzük azt ki, és ugyanígy hiába vagyunk a cselekvő hétköznapi állapotainkban, ha nem az Isteni Tudatból ihletődünk. Így az Istennel való helyes kapcsolat azt jelenti, hogy tudatosan meg kell ismernünk a mély állapotainkat, melyek azonosak az Isteni Tudattal, ám ugyanakkor az ott megtapasztalt érzéseket ki is kell fejeznünk a hétköznapokban, normális emberi tudatállapotban.

Ennek a felismerésnek ugyanakkor van egy lényeges oldala is. Hiszen, amennyiben a mi legmélyebb tudatállapotunk azonos az Isteni Tudattal, akkor a legmélyebb vágyaink - legyenek ezek akár személyes vágyak is - azonosak az Isteni Akarattal. Természetesen csakis a tiszta (a neveltetésből származó téves ítélkezéstől független), mély vágyak lehetnek azonosak az Isteni Akarattal. Azt is fontos megjegyezni, hogy csakis egy lelkileg többé-kevésbé tiszta ember képes az igazi, mély vágyait tudatosítani és ugyanakkor meg is élni. A lényeg az, hogy sok tévhittel szemben, az Isteni Akaratot a legtisztább formában nem kívülről, hanem a lelkünkben, belülről ismerhetjük igazán fel. Természetesen ez azt is jelenti, hogy az az ember, aki eddig is többé-kevésbé az igazi vágyaitól vezérelve élt, igenis, részben vagy teljes egészében beteljesítette az Isteni Akaratot, még akkor is, ha tudatosan nem is hitt Istenben. Más szavakkal mondva: az Isteni Akarat nem egyéb, mint a bennünk élő legmélyebb, legmerészebb vágyainknak a felismerése és beteljesítése. Erre vonatkozóan gyakorlatilag minden hiteles vallás vagy bölcs emberek tanításaiban fellelhetünk bizonyítékokat. Minden igazi bölcs és szent egyértelműen arról beszél, hogy Isten a szívünkön keresztül szól hozzánk, hogy csakis a szívünket követve tudunk Istenhez jutni. Mielőtt tovább mennénk, meg kell néznünk, hogy miként szerethet bennünket az Isten.

== Isten Szeretete

A kereszténység csodálatos munkával tudatosította bennünk, hogy a Világegyetem Teremtője szeret bennünket. A gond csak azzal van, hogy sokan nem tudjuk, hogy ez gyakorlatilag mit jelent vagy sokan egyenesen nem hiszik el ezt az igazságot.

Nézzük meg, hogy mit is jelenthet Isten felénk irányuló szeretete?

Isten szeretete lényegében nem lehet más, mint az emberek által is tapasztalt szeretet, hiszen a szeretet az egész Univerzumban csak egy van: maga a *Szeretet*. Ezt a szeretet kell éreznünk mi is, amikor szeretünk, de ugyanakkor Istennek is magát a *Szeretetet* kell felénk sugároznia. Ezzel csak azt akarom érzékeltetni, hogy az úgynevezett emberi és isteni igaz szeretet között lényegében nagy különbség nem lehet, esetleg csak annyiban, hogy Isten szeretete tökéletes, tehát folytonos és intenzív. Ha ebből az igazságból indulunk ki, akkor a saját szeretetünk alapján következtetni tudunk arra, hogy miképpen szerethet bennünket Maga az Isten. Ha mi valójában szeretünk valakit, akkor egyértelműen, tiszta szívvel azt akarjuk, hogy a szeretett személy vágyait valamilyen úton-módon beteljesítsük, őt csodálatos meglepetésekkel elhalmozzuk, boldoggá tegyük és segítsük az előrehaladását valódi céljainak elérésében. Amennyiben ezt nekünk sikerül elérnünk, akkor mi is boldogok leszünk. Természetesen, ha a mi szeretetünk ekképpen működik, akkor mennyire inkább ugyanígy fejeződik ki az Isteni Szeretet? Bár azok számára, akik sokat szenvedtek vagy szenvednek az életükben, elképzelhetetlennek tűnhet, igenis maga az Isten Szeretete is az előbb levezetett séma szerint működik, méghozzá folytonosan és tökéletesen. Ez azt jelenti, hogy Isten akkor a legboldogabb, ha a vágyainkat beteljesítheti! Sőt ez azt is jelenti, hogy Isten - mint a Maga a Tökéletesség - minden körülményt már meg is tervezett ahhoz, hogy vágyainkat beteljesíthessük. Akár hisszük, akár nem, Isten tökéletesen előkészítette életünket, még születésünk előtt. Ez azt jelenti, hogy Isten egy teljesen boldog életfeltételt teremtett meg, melyekben mi csodálatos és sok ember számára elképzelhetetlen, eksztatikus boldogságokban kellene éljünk. Természetesen, ez az igazság csakis Isteni szempontból érvényes. Lehetséges például, hogy szegény, nélkülözésben élő családba születtünk, ám ennek (a szegénységnek) legyőzése olyan elégtételt, önbecsülést, nemességet adna lelkünknek, melynek segítségével életünk egy folytonos elégedettségben zajlana, miáltal másoknak is megmutathatnánk a kiutat. Erről előadásokat tarthatnánk, könyveket írhatnánk és így szeretetünk, csodálatos életünk révén számos ember életét megmenthetnénk, szomorú helyzetüket megváltoztathatnánk. Ha ezt tennénk, akkor valójában beteljesíthetnénk Isten Tervét és egy hihetetlen, sikerekben gazdag életet élhetnénk, ahol más emberek szenvedéseinek enyhítése, legyőzése egy folytonos, csodálatos állapotban tartana bennünket. Ekkor tudnánk, hogy az életünknek van értelme, hogy boldogságra és szeretetre hívattunk. Természetesen Isten e csodálatos életünk minden lépését már előkészítette, így nekünk csak érzéseinkre hallgatva követnünk kell mély vágyainkat, melyek azonosak az Isteni Tervvel, vagyis azzal az isteni vággyal, amely minket a tökéletes boldogsághoz vezet. Ebben a példában láthatjuk, hogy valójában lelkünk akarta, hogy szegény családba szülessünk, hiszen csakis a szegénység legyőzése által válhattunk hitelesekké mások előtt. Csak így teljesíthettük be életfeladatunkat, mely számunkra a lehető legnagyobb boldogsággal azonos. Amennyiben egy gazdag családban láttuk volna meg a napvilágot, hiába magyaráztuk volna másoknak, miképpen győzhetik le a szegénységet, azt mondták volna - méghozzá jogosan -, hogy nekünk könnyű, hiszen azt sem tudjuk, mi a szegénység, így szavunk hitelét vesztette volna. Ezzel a példával érzékeltetni akartam, hogy mit is jelenthet Isteni szempontból egy csodálatos élet előkészítése. Ám mi van akkor, ha mi ezt a feladatot nem ismerjük fel, ha nem hallgatunk alázatosan a lelkünkre? Természetesen, akkor szerencsétlennek tartanánk magunkat, hiszen egy lehetőségekben gátolt családban születtünk, ahol még az egyetemre sem jutott pénzünk, lehet, hogy még Istent is hibáztatnánk sorsunkért, esetleg Isten létezését is megkérdőjeleznénk, szeretetét pedig mindenképpen. Ezáltal pedig tehetetlennek éreznénk magunkat, szomorú és szerencsétlen életet élnénk. Ám Isten ezért nem hibás, Ő az elképzelhető legcsodálatosabb életet készítette elő nekünk, ám mi mégis, szabad akaratból, gyengeségből stb. - a könnyebb utat választva - elrontottuk életünket. Isten végtelen szeretete mindannyiunk legmerészebb álmát akarja beteljesíteni. Ezek az álmok egyénre szabottak, de egy dologban megegyeznek: olyan csodálatosak, hogy első látásra hihetetlennek tűnik megvalósításuk. Isten nem kicsinyes. Isten olyan boldog életet készített elő nekünk, mely felülmúl minden képzeletet. Isten megadta a maximális boldogságra való lehetőséget, sőt, testünket, lelkünket, egész életünket erre a csodára programozta. Ez a program tulajdonképpen az Isteni Akarat. Ez a program, természetesen, azonos a legmélyebb, legmerészebb vágyainkkal. Hiszen mi, amikor igazán lelki, mély tudatállapotban vagyunk, akkor tulajdonképpen a mindenütt - így a bennünk is - létező Isteni Tudattal vesszük fel a kapcsolatot, mely a szívünk révén megmutatja az Isteni Tudatból fakadó vágyainkat.

Egyszóval Isten annyira szeret minket, hogy a tökéletes boldogságban akar bennünket látni, és, higgyék el, nem adja alább. Lehet, hogy éppen ezért nem értjük meg Őt, mert magas a mérce, mert Ő nem a fél, hanem a Teljes Boldogságot készítette elő számunkra.

== Az Isteni Akarat azonos az életúttal

Minden ember pontos feladattal születik a Földre. Ezt élete során vagy beteljesíti, vagy nem. Minden létező dolog a Földön egy vagy akár több, jól meghatározott feladattal rendelkezik. A szék azért van, hogy ráüljenek, az ablak, hogy rajta keresztül kiláthassanak, a fa, hogy számos funkciót betöltsön a Föld ökoszisztémájának fenntartásában, a jégmezők úgyszintén betöltik a maguk szerepét stb. Természetesen, ha mindennek feladata van, akkor az embernek is, méghozzá nem is kicsi. Ugyanakkor azt is tudnunk kell, hogy ez a feladat testre szabott, a képességeink, tehetségeink függvényében. Persze megjegyzendő, hogy sok esetben képességeinket nagymértékben növelni tudjuk! Minden ember csodálatos és nagy feladattal született, hiszen csak ennek a beteljesítésével érhetjük el az Isteni Tervben szereplő hihetetlen boldogságokat. E feladatra felkészülve minden ember felismeri hatalmas és csodálatos képességeit, megízlelheti a szabadságot, azt a tényt, hogy Isten a Saját képére és hasonlatosságára teremtett bennünket, azt a tényt, hogy gyakorlatilag bármire képesek vagyunk, ha követjük az Isteni Akaratot. Minden ember életútja gyakorlatilag arról szól, hogy önmagát megismerve kifejezze és megvalósítsa mély vágyait, ezáltal pedig átalakítsa környezetét az Isteni Harmónia szerint. Baden Powell, a Cserkészmozgalom megalapítója, végakaratában ezt üzente cserkészeinek: _"Hagyjátok szebben a Földet, mint ahogyan kaptátok."_ Ő be is tartotta szavát, több millió gyermeknek mutatta meg a boldogság, a szeretet egyik lehetséges útját. Mondása jól tükrözi, hogy mit vár el tőlünk az Isten: a környezetünk vagy akár a Föld átalakítását. Minden ember egy bizonyos területen a legjobb. Ezt kell megtalálnunk, ezt kell magunkban felismernünk, majd pedig megélnünk és a valóságban felépítenünk. Ha őszinték vagyunk és életünket még nem hálózta be a fásultság, akkor még vissza tudunk emlékezni a legmerészebb vágyainkra, melyeket megvalósítva csodálatos életet élhetünk. Képzeljük el, hogyha egy jó tündér azonnal minden vágyunkat teljesítené, akkor mit kérnénk tőle? Őszintén tegyük fel magunkban a kérdést, hogy akkor mi lenne az, ami a legnagyobb boldogságot adná számunkra? Ha őszintén feltesszük ezt a kérdést, akkor meg fogjuk rá kapni a választ. Lehetséges, hogy eleinte csak részben, de biztosan megérezzük majd, hogy milyen irányban induljunk el, ahhoz, hogy teljes legyen majd a kép. Az is igen valószínű, hogy eleinte nem fogjuk elhinni, azt, hogy mi képesek lennénk ezeket a vágyakat megélni, ám ekkor majd meglátjuk, hogy, ha mi valóban felvállaljuk vágyaink megélését, akkor Isten elvezet azok konkrét megvalósításához. Természetesen ez a folyamat csak idővel és az isteni bölcsességnek megfelelően, fokozatosan valósulhat meg. És természetesen ez a folyamat csak akkor teljesülhet be igazán, ha mi következetesen hallgatunk a lelkünkre, ha mi alázatosan követjük az Isteni Akaratot.

Ha már az Isteni Akaratról beszélünk, el kell mondanom, hogy általában minden ember estében Isten a következőket akarja: hogy legyen egy egészséges, szép testünk, hogy táplálkozzunk helyesen, hogy sok természetes vitamint, ásványi anyagot stb. fogyasszunk, hogy sokat legyünk a természetben, hogy anyagilag jól szituáltak legyünk, hogy pihenjünk eleget, hogy szerelemmel telített és beteljesítő szexuális életet éljünk, hogy sokat szórakozzunk, nevessünk, hogy spirituális szempontból fejlődjünk, hogy szeressük egymást. Ezért ezeket a dolgokat már most elkezdhetjük. Persze lesznek olyan személyek, akik meg fogják érezni, hogy egyes pontok az előbb felsoroltak közül nem érvényesek számukra (pl. egy elhivatott apáca esetében a nemi élet).

== A rezonancia törvénye

Ahhoz, hogy valójában megértsük az átkódolás folyamatát, még egy természeti törvényt meg kell ismernünk. Ez a törvény a rezonancia törvénye. A rezonancia törvénye kimondja, hogy hasonló, csak hasonlóval rezonál. Vagyis, hasonló csak hasonlót tud magához vonzani. Ennek a törvénynek a nagyon szép bemutatása megtalálható "A Titok" (The Secret) című könyvben és filmben. Egyetlen dolog, amit óvatosan kell kezelni ebben a könyvben vagy a filmben az, hogy nem hangsúlyozza ki eléggé az Isteni Akarat fontosságát. Ezért az ott tanultakkal óvatosan kell bánni, hiszen, ha el akarunk érni valamit és az a cél nem egyezik az Isteni Akarattal, akkor nagyon valószínű, hogy az nem is fog sikerülni.

A rezonancia törvénye kimondja, hogy életünk, sorsunk és körülményeink, tulajdonképpen a mi mély érzéseink, gondolataink miatt olyanok, amilyenek. Például, ha mi mindig mindent pesszimistán látunk, akkor rezonálunk a pesszimizmussal, ezáltal pedig bevonzzuk a szerencsétlen helyzeteket. Ha viszont, mélyen hiszünk abban, hogy egy szebb jövő vár ránk és teszünk is ennek eléréséért, akkor az idővel be is következik. A Világegyetemben minden, ami létezik - még a gondolatok, érzések is - folyamatosan egy jól meghatározott frekvencián vibrálnak. A hasonló rezgések pedig vonzzák egymást. Minden szokásunk, gondolatunk, érzelmünk egy bizonyos frekvencián rezeg. Ha találkozunk egy olyan emberrel, aki hozzánk hasonló frekvenciákkal rendelkezik, akkor szimpátiát érzünk iránta. Ha pedig találkozunk egy olyan emberrel, akinek a frekvenciája eltérő a mienktől, idővel el akarunk távolodni tőle. Igen ám, de ugyanígy rezonálhatunk például a betegségekkel is, hiszen minden betegségnek van egy bizonyos frekvenciája. A természetgyógyászat már le is írta, hogy melyik betegség milyen állapotok miatt következik be. Például a legtöbb esetben a vese a félelem állapota, rezonanciája miatt betegszik meg. A rák pedig az életúttól, való nagy eltérés miatt jön létre. Ezek a törvények a gyermekek esetében is érvényesek, hiszen ők is tudat alatt már pár hónapos korukban dönthetnek helyesen vagy helytelenül. A baleset szintén a bennünk levő rezonancia miatt következhet be. Ha, például, túlhajszoljuk magunkat, akkor rezonálhatunk azzal a vággyal, hogy pihenjünk így ezt egy balesettel el is fogjuk érni. Ugyanígy, ha például, rezonálunk a siker állapotával, akkor könnyedén sikeresek lehetünk bármilyen területen. A rezonancia törvényére még számos példát lehetne adni, ám inkább nézzük meg, hogy az átkódolás esetében mivel fogunk rezonálni.

Az átkódolás pillanatától, kezdődően rezonálni fogunk az Isteni Akarattal. Ez azt jelenti, hogy olyan magasrendű energiákkal fogunk kapcsolatba kerülni, melyek idővel gyökeresen megváltoztathatják életünket. Amennyiben megkaptuk az átkódolást, a rezonancia törvénye értelmében folyamatosan rezonálni fogunk olyan eseményekkel, melyek az Isteni Akarat, vagyis az életút beteljesítése irányába fognak bennünket vezetni. Olyan új lehetőségek fognak feltárulni előttünk, melyek lényegileg át tudnak majd alakítani bennünket. Kialakulhat egy jobb párkapcsolat, új barátság, esetleg megváltozhat a jelenlegi. Találkozhatunk egy új munkalehetőséggel, felismerhetünk számos bennünk létező, eddig nem tudatosított jellemhibát, lehet, hogy érdekelni kezd majd bennünket az Isteni Törvények működése stb. Egy másik lényeges dolog pedig az lesz, hogy egyre kevésbé fogunk rezonálni a *rosszal*. Fel fog ébredni bennünk egy vágy arra vonatkozóan, hogy rossz szokásainkat elhagyjuk és hogy melegszívű, jóságos emberek legyünk. Ezek az érzések nagyon kellemes állapotokat fognak bennünk megteremteni, fokozatosan érezni fogjuk, amint egyre inkább önmagunkká válunk, ami egy magasrendű önbecsüléshez, magabiztossághoz, illetve megelégedettséghez fog elvezetni. Ugyanakkor idővel egyre kevésbé fogunk rezonálni a balesetekkel, a betegségekkel, a sikertelenséggel, az egoizmussal.

Természetesen, mindezek a folyamatok csak idővel és fokozatosan fognak bekövetkezni. Ugyanakkor ezek a folyamatok változásokat fognak előidézni bennünk, melyeket a szabad akaratunk révén lassíthatunk vagy gyorsíthatunk. Azt is fontos tudnunk, hogy nem vagyunk egyformák, így lehetséges, hogy egyes emberek, amennyiben eddig lelkileg nem voltak elég tiszták, először egy megtisztulási folyamaton kell átmenjenek és csak utána indulhatnak el a további események. Egy dolog viszont biztos. Az átkódolás után meg fogjuk érezni a változás erejét, melynek továbbfejlődését a szabad akaratunk révén csökkenthetjük, vagy fokozhatjuk, de megállítani nem tudjuk.

== Hogyan valósul meg az átkódolás?

Először is az átkódolást csak olyan ember tudja tovább adni, aki már megkapta. Onnantól kezdve, hogy valakitől megkapjuk az átkódolást, rendelkezünk azzal a képességgel, hogy bárkinek ezen a Földön továbbadhassuk. Ez azt jelenti, hogy egész életünkben képesek leszünk bárkinek az életét Isten segítségével a jó irányba terelni, a boldogság fele irányítani. Ez a képesség hatalmas kincs lesz, mely felelősséggel jár. Innentől kezdve, amennyiben bármelyik embertársunk beleegyezik, segítségünkkel megkaphatja az átkódolást. Ez pedig nem jelent egyebet, mint szerepvállalást a társadalmunk megváltoztatásában, a világ jobbá tételében, a problémáink megoldásában. Az átkódolás megkapása után már nem leszünk tehetetlenek, ugyanis képesek leszünk nagyon sokat tenni barátainkért, családunkért, embertársainkért. Éppen ezért, ha valaki megkapja az átkódolás képességét, jó lenne, ha átérezné a továbbadás szükségességének felelősségét is.

Amikor valakinek át akarjuk adni az átkódolást, jobb kezünket kényelmesen kinyújtva helyezzük az illető fejére, úgy, hogy tenyerünk az illető homlokán legyen elhelyezve. Ujjaink legyenek kinyújtva és enyhén szétnyílva. Az átkódolás során ülhetünk vagy állhatunk is, a lényeg az, hogy kényelmes testtartásban legyünk. Miután kezünket az illető fejére helyeztük, behunyt szemmel és teljes hittel mondjuk magunkban a következőket:

[quote]
"Uram Istenem, Égi Atyám, tudom, hogy Te bármire képes vagy. Tudom, hogy, ha akarod, akkor a velem szemben levő Pált (elmondjuk az illető ember keresztnevét) pár percen belül örökre megváltoztathatod. Kérlek, itt és most a végtelen képességeddel kódold át őt. Tudom, hogy amint ezt megteszed, Pál örökre meg fog változni és innentől kezdve más ember lesz az idők végezetéig. Kérlek hát, kódold át őt. Kérlek, ismét tégy csodát, és újra mutasd meg Végtelen Kegyelmedet, kódold át itt és most Pált."

Amint ezt a kérést teljes hittel elmondjuk, érezni fogjuk ugyanazt az erőt, amit mi akkor megéreztünk, amikor megkaptuk az átkódolást, amint felülről lefele, szinte magától, ám mégis erőteljesen áramlani kezd, majd a kezünkön keresztül a velünk szemben levő személy testébe átáramlik. Az átkódolás időtartama átlagban 16 perc kell legyen. Ez idő alatt többször is kérhetjük Istent, hogy kódolja át a velünk szemben található személyt, tehát többször is elmondhatjuk az átkódolás szövegét.

Ahhoz, hogy az átkódolás jól sikerüljön, a következő állapotban kell legyünk: egy nagyfokú magasztos és szentséggel telt állapotban. Tudnunk kell, hogy Isten Tervének részesei vagyunk. Tudnunk kell, hogy, igenis, az átkódolás során a világ megmentésén fáradozunk. Egy hatalmas, Istentől származó dicsőséget kell éreznünk, amely minden rosszat megsemmisít és amely bármit képes megváltoztatni, átalakítani. Biztosan kell tudnunk, hogy az átkódolás során a velünk szemben levő személy is részese lesz az isteni terv beteljesedésének. Ő is ahhoz a nagy családhoz fog tartozni, mely visszatért az Isteni Akarat elfogadásához. Állapotunk hasonlatos kell legyen ahhoz az állapothoz, mint amikor Jézus tanítványai kézrátétellel gyógyíthatatlan betegeket gyógyítottak meg. Ott is, akkor, egy magas fokú szentség állapota volt jelen. Tulajdonképpen az átkódolással mi hasonló dolgot fogunk tenni, mint amit Jézus tanítványai tettek, csak ezúttal Isten a mi segítségünkkel elsősorban a lelket alakítja át, nem a testet. Egy másik nagyon fontos dolog az, hogy az átkódolás során, nekünk mindvégig erősen akarnunk kell, hogy a folyamat megtörténjen. Olyan erősen, hogy könyörgésünk erejével valóban beindítsuk az átkódolás folyamatát. Annyira erősen kell akarnunk, hogy a másik személyben megtörténjen az átalakulás, mintha ez a folyamat élet-halál kérdése lenne. Ám, ha belegondolunk, valójában az is. Ugyanakkor hagynunk is kell, hogy az átkódolás megtörténjen. Egy tökéletes egyensúlyban kell lennünk, ahol az akarat és az engedés kiegyenlítődik. Ahhoz, hogy ezeket az állapotokat könnyebben megéljük, nagy segítségünkre lehet egy magasztos zene. Én javaslom *Hans Zimmer* a "The DaVinci Code" filmzene albumának a "*Chevaliers de Sangreal*" című számát. Ez a szám nagyon jól kifejezi a szentség és magasztosság állapotát. Az is segítségünkre lehet, hogy 4 perces, ami azt jelenti, hogy amennyiben négyszer lejátsszuk, lejár a 16 perc, tehát az időmérést is elősegíti.

Most egy nagyon fontos tényezőre hívnám fel a figyelmet. Minden esetben, mielőtt átadnánk az átkódolást, kötelező, hogy a jelölt személlyel, ismertessük ennek előnyeit és következményeit. Ez azt jelenti, hogy vagy el kell előtte olvasnia az átkódolás leírását, vagy pedig nekünk kell vele részletesen ismertetnünk azt. Kötelező, hogy minden ember csakis és kizárólag szabad akaratából, a következményeket ismerve és felvállalva kaphatja meg az átkódolást! Ellenkező esetben az illető ember beleegyezése nélkül beleavatkozunk az ő szabad akaratába és megváltoztatjuk az életét. Ez ránk nézve is súlyos következményekkel fog járni! Ezért megkérek mindenkit, hogy soha ne szegje meg ezt a szabályt. Mindenkinek joga van szabadon eldöntenie, hogy akar-e egy Isten által irányított életet leélni, vagy sem? Ne feledjük el, hogy, ha Maga Isten is ezt a törvényt mindig tiszteletben tartotta, akkor nekünk sem szabad áthágnunk. Nem szabad senkit sem a kellő tájékoztatás nélkül átkódolnunk! A szabad akaratba való beavatkozás a világ egyik legsúlyosabb bűne. Mi soha - még gondolatban sem - tehetünk ilyent. Ha pedig valaki mégis megtenné, számolnia kell tettének súlyos következményeivel!

== Kik nem kaphatják meg az átkódolást?

Mivel az átkódolás az egyik legkifinomultabb energia, eleinte megviselheti a problémákhoz, tehetetlenséghez, valamint a kemény élethez szokott testünket. Ugyanis az átkódolás, mint az Isteni Akarat finom energiája, fokozatosan átalakítja testünket, az alacsonyabb szintű rezgéseinket idővel magasabbra hangolja át. Természetesen ezek az átalakulások néhány esetben komolyabban is megviselhetik testünket. Bár lehet, hogy túlzottan óvatos vagyok és az is lehet, hogy nincsen teljesen igazam, mégis úgy gondolom, hogy egyes esetekben nem szabad megadni az átkódolást vagy csak saját felelősségre és nagyon óvatosan. Úgy gondolom, hogy az öt éves kor alatti gyermekek esetében jobb, ha nem kapják meg az energiát. 16 éves korig pedig úgy látom, hogy jobb, ha csak 4-5 perces átkódolást kapnak, sőt az is javasolt, hogy az első esetben csak 2 perces legyen az átkódolás. Amennyiben ez a 2 perc nem borítja fel a testi egyensúlyt, akkor idővel lehet 4 percesre emelni, ha ebben az esetben sem észlelünk valamilyen problémát, akkor -- természetesen - fokozatosan elérhetjük a 10-15 perces átkódolást is. Ugyanígy nem ajánlott súlyos betegek esetében átadni az átkódolást, hiszen egy legyengült test ezt az energiát nem tudja problémamentesen elviselni. Különösképpen nem ajánlott magas vérnyomásos, illetve súlyos szívbetegek esetén (pl. akiknek pacemakerük, műtétileg beültetett szívritmus szabályzójuk van) vagy olyan emberek esetén, akiknek embóliájuk, trombózisuk van, hiszen a nagy energia megindíthatja a testben még feloldatlan állapotban levő vérrögöket. Ugyancsak nem ajánlott súlyosabb mirigy-problémákkal rendelkező betegek esetén, főleg pajzsmirigy-betegségek esetén. A vese- illetve időnként májbeteg emberek esetében sem ajánlom az átkódolást, vagy csak nagyon óvatosan, először egy percig és, ha nem lépnek fel rendellenességek, csak akkor ajánlom, hogy 2-3 perces, majd pedig idővel hosszabb időtartalmú átkódolásban részesüljenek. Ugyanakkor figyelmesen és óvatosan járjunk el az olyan emberek átkódolása esetén is, akik nem rendelkeznek kellő vitalitással. Jobb, ha ők eleinte csak kb. 8 perces átkódolásban részesülnek. Mindenkit megkérek, hogy tartsa be ezeket az utasításokat, hiszen célunk a jót elterjeszteni, nem pedig kisebb-nagyobb problémákat okozni. Mindenki az átkódolás kezdete előtt kötelező módon kérdezze meg, hogy az átkódolandó személynek van-e valamilyen betegsége és amennyiben súlyos, vagy az előbb felsorolt betegségekkel találkozik, akkor, kérem, ne hajtsa végre az átkódolást. Fontos azt is tudnunk, hogy a rákos betegeken nagyon sokat segíthet az átkódolás gyógyító ereje. Ám az ők esetében is ügyelnünk kell arra, hogy amikor megkapják az átkódolást ne legyenek a krízis állapotában és viszonylag legyenek egy életerősebb periódusukban. Ha pedig már előrehaladott állapotban levő rákos betegről van szó, akkor óvatosan és fokozatosan, az előbb leírt módon adjuk át az átkódolást. Természetesen ebben az esetben is az igen súlyos fázisban levő betegeknél nem ajánlott az átkódolást megadni vagy csak saját felelősségre és nagyon óvatosan. Az öregek esetében is óvatosabban kell eljárnunk. Náluk eleinte 4-6 perces átkódolást ajánlok, utána pedig, amennyiben nem észlelünk rendellenességeket, pár nap múlva fokozhatjuk az időtartamot 10 percesre és, ha akkor sincsen semmi probléma, akkor néhány napon belül elvégezhetjük a 16 perces átkódolást.

Egy másik figyelmeztetést is el kell mondanom. Amikor egy ember végrehajtja az átkódolást, ő is ismét részesül benne. Ám, főleg eleinte, testünk nehezen viseli el a sok átkódolást. Ezért azt javaslom, hogy eleinte, maximum, naponta csak egy átkódolást végezzünk el, ha pedig erős, vitális testtel rendelkezünk akkor esetleg hármat. Időnként pedig tartsunk egy-egy nap szünetet. Nagyon fontos tudnunk, hogy, amint kezdünk érezni egy, az átkódolással energiájával való túltelítődést, azonnal álljunk le és tartsunk egy pár napos szünetet. A szünet alatt jó, ha kint tartózkodunk a természetben, ha feltöltődünk, hogy utána képesek legyünk az újabb átkódolások elvégzésére. Nagyon fontos, hogy amint érezzük a túltelítődést egyetlen átkódolást se adjunk tovább vagy egyetlen átkódolást se kapjunk, hiszen testünk ebben az esetben kezdi elérni a tűrőképessége határát és amennyiben még egy átkódolásban részesülünk, túlléphetjük a határt és akár több hetes vagy hónapos betegség üthet le a lábunkról. Gondolom, ez sem nekünk, sem pedig másoknak nem hiányzik. Azért mondom ezt el, mert volt, aki naponta több mint 20 átkódolás elvégzése után, a harmadik nap hirtelen kb. két hónapig ágyban fekvő beteg lett. Volt olyan eset is, hogy napi három átkódolás után, valaki csak remegő térdekkel tudott járni és nem volt képes egész nap semmi hétköznapi teendő elvégzésére, valamint nagyon sokat kellett aludnia. Ezért ebben az esetben is, mindenkit óvatosságra intek. Több átkódolást csak úgy lehet elvégezni, ha nagyon erős testtel rendelkezünk, ha sokat vagyunk a természetben, egyszóval, ha jó nagy az életerőnk. Milyen következményekkel járhat az átkódolás?

Az eddigi egy éves tapasztalatunk alapján, mely időtartam alatt több mint ezeren részesültek az átkódolásban (feltételezem, hogy ezen anyag megjelenése sokkal nagyobb számban fogja elterjeszteni az átkódolást), számos tapasztalattal lettünk gazdagabbak, melyeket most megosztanék a Tisztelt Olvasóval.

Amikor megkapjuk az energiát, ha érzékenyebbek vagyunk, egy csodálatos, Istennel történő kapcsolatfelvételt fogunk észlelni. Ez egyes emberekben kiválthatja akár a katarzis állapotát is. Néhány napig alvásunk sokkal mélyebb lesz, megnőhet az alvásigényünk is. Ez jó, hiszen, amíg alszunk, dolgozni tud rajtunk az energia és gyorsíthatja az átalakulás folyamatát. Néhány nap alatt sok minden átértékelődhet bennünk, új, tiszta vágyak ébredhetnek fel lényünkben, könnyedén lemondhatunk a rossz szokásainkról, hiszen azok már nem fognak vonzani. Amennyiben sem az átkódolás során, sem pedig utána nem igazán fogunk semmit sem érzékelni, akkor, többször is ismételtessük meg az átkódolást vagy pedig mi magunk adjuk tovább azt többször, hiszen így jól fel tudunk töltődni vele és előbb-utóbb érzékelni fogjuk jótékony hatásait.

Egy másik fontos dolog, hogy amikor valakinek átadjuk az átkódolás energiáját, közvetlenül utána tanítsuk meg neki is, hogy hogyan kell ezt végezni, és kérjük meg, hogy ő, még akkor, adja is vissza az átkódolást. Ennek két előnye lesz. Az egyik, hogy le tudjuk ellenőrizni, jól végzi-e az illető, a másik pedig az, hogy önbizalmat adunk neki, belátja, hogy ő is képes továbbadni az átkódolást. Amennyiben nem sikerül jól visszaadnia az illető személynek az energiát, vagyis nem érezzük, hogy az erőteljesen belénk áramolna, akkor tudnunk kell, hogy ennek csak néhány oka lehet. Az egyik az, hogy nem hiszi el, hogy ő erre képes, vagy nem hisz eléggé Istenben, a másik az, hogy túlságosan is akarja, hogy sikerüljön és ezáltal nem hagyja eléggé, hogy Isten végezze a dolgát vagy pedig, éppen ellenkezőleg, túlságosan is passzívan csak elvárja, hogy magától bekövetkezzenek a dolgok. A passzivitás nem jó, hiszen annyira erősen kell akarnunk nekünk is, hogy megtörténjen a szemben levő személy megváltozása, mintha ez élet-halál kérdése lenne, tehát igen erősen kell egész idő alatt kérnünk Istent, hogy ismét megtegye a csodát. A sikertelenségnek lehet egy olyan oka is, hogy az illető személy nem tudja átélni eléggé a szentség állapotát. Ebben az esetben nem fogta fel az átkódolás jelentőségét. Az előbbi részben elmondtam, hogy főleg eleinte, naponta csak egy átkódolást végezzünk. Természetesen ebben benne van az is, hogy miután megtanítjuk az átkódolt személyt az átkódolásra, ő azt vissza is adja, hogy leellenőrizhessük, megértette-e, hogy hogyan kell ezt végezni. Így naponta két átkódolásban is részesülhetünk, mindaddig, amíg nem érezzük, hogy túltelítődünk vele. Ha érezzük a túltelítődést, hosszabb szünetet kell tartsunk.

Tapasztalataink alapján tudjuk, hogy kb. 4-8 hónap szükséges ahhoz, hogy testi szinten megtörténjen az átkódolásra való teljes ráhangolódás, vagyis a testünk ennyi idő alatt tud az Isteni Akarat szerint átalakulni, rezgésszámunk (frekvenciánk) ennyi idő alatt fog egy alapvető magasabb frekvenciára emelkedni. Természetesen a továbbiakban is emelkedni fog a rezonanciánk, ám a 4-8 hónap alatt egy alapvető átalakulás fog végbemenni a testünkben. Ennek az átalakulásnak a folyamata annak függvényében fog lassabban vagy gyorsabban végbemenni, hogy mennyire tiszta, egészséges, illetve életerős a testünk. Ugyanakkor nagymértékben meggyorsíthatjuk az átalakulás folyamatát, ha mi magunk is akarjuk a változást, ha alázatosan engedjük, hogy Isten akarata átvegye felettünk az irányítást. Amennyiben viszont egoista módon tovább akarjuk folytatni a rossz szokásainkat, lassítjuk az átalakulást, kihívhatjuk magunk ellen a sorsot, esetleg betegekké is válhatunk. Az igazság az, hogy egyes esetekben még akkor is kialakulhat testünkben kisebb-nagyobb betegség, ha kevésbé vagyunk egoisták, hiszen az átkódolás időnként olyan mértékű tisztulási folyamatokat indít el bennünk, melyek akár betegséget is okozhatnak. Ha ez bekövetkezik, ne ijedjünk meg, mert a tisztulás után testileg is és lelkileg is sokkal jobban fogjuk érezni magunkat, mint előtte.

Az átkódolás különböző vágyakat fog felébreszteni bennünk. Ezek lehetnek spirituális vágyak, de lehetnek profán vágyak is. A lényeg az, hogy kövessük őket, mert ezeknek a beteljesítése közelebb fog vinni Istenhez. Volt olyan, aki az átkódolás után ráébredt arra, hogy nem élvezte eléggé az életet és azóta többet kirándul, többet jár színházba, több időt tölt szerelmével. Volt olyan eset is, amikor valaki rájött, hogy ő sokkal szegényebb, mint ahogy azt eddig akarta, így az anyagi problémáját orvosolta az átkódolás után. Volt, aki felismerte, hogy mennyi illúziója van, nagyon sokan részben vagy teljesen leszoktak rossz szokásaikról. Sokan azóta komolyabban vették a kapcsolatukat Istennel, vagyis jobban hisznek a szívüknek és könnyebben követik azt.

A 4-8 hónap lejárta után melegebb szívűekké válunk. Ez tulajdonképpen az átkódolás lényege. A melegszívűség azt jelenti, hogy kedvesebbek leszünk, finomabb lelkületűek, gyöngédebbek. Jobban fogjuk értékelni a családi meleget, a szép párkapcsolatot; megelégedettebbek, nyugodtabbak, lelkiismeretesebbek és egyszerűbbek leszünk és sokkal, sokkal jóságosabbak. Valósággal a jóság megtestesülésévé válunk. Isten azt mondta, hogy ez az átkódolás lényege. Ugyanis a jóság megélése által változhat meg hideg, sokszor lelketlen társadalmunk. Azt is mondta, hogy amikor a Föld legtöbb embere melegszívű lesz, akkor egész egyszerűen nem fogunk rezonálni a problémákkal, a szegénységgel, a katasztrófákkal, így könnyedén el fogjuk kerülni azokat. Akkor egoizmus nélkül, becsületesen fogjuk végezni életutunkat. Amikor jóságosak leszünk, akkor érezni fogjuk, amint egyre inkább önmagunkká válunk, amint egyre inkább ráhangolódunk egy vezetettségre, egy kifinomult szeretet-energiára, ami fokozatosan minden gondunkat megoldja és ami egyre mélyebbé, boldogabbá fog tenni bennünket. Isten elmondása szerint, miután elérjük a jóság állapotát, még körülbelül 4-5 év kell ahhoz, hogy az átkódolás folyamata a mindennapi életünkben is, vagyis a fizikai síkban is teljesen kifejtse a hatását. Ez azt jelenti, hogy átlagban ennyi idő kell ahhoz, hogy a mindennapokban is azt kezdjük el cselekedni, ami az Eredeti Isteni Akarat. Tehát az átkódolás folyamata kb. 5-6 év.

Egy másik jelenség is meg fog történni. Idővel érezni fogunk egy könnyed, természetes lelki stabilitást. Ez a másik bizonyítéka az átkódolás hatékonyságának. Ez egy fantasztikus érzés. Annak az érzékelése, amikor tudjuk, hogy jó úton haladunk, amikor biztosak vagyunk dolgunkban, amikor már alig, vagy egyáltalán nincs bennünk kétség. Ez egy folytonos, laza, könnyed boldogsággal fog járni. Bár ezután is lehetnek még problémáink, sokkal könnyedebben fogjuk kezelni és megoldani azokat. Ami még nagyon fontos ebben az állapotban az az, hogy felismerjük, hogy ez örökre megmarad, hogy elveszíthetetlen. Egyszóval érzékelni fogunk egy örök kapcsolatot Istennel, ha nem is feltétlenül tudatosan, de legalább tudat alatt.

Idővel, bár egyes esetekben már közvetlenül az átkódolás után is, bekövetkezhet, hogy a tárgyak, élőlények, jelenségek hangulatát jobban fogjuk érzékelni. Ez egy komoly spirituális szint elérésének a bizonyítéka, hiszen azt jelenti, hogy elménk már kevésbé dominál bennünket. Azt jelenti, hogy nyitottabbak vagyunk és többet érzékelünk a valóságból. Azt jelenti, hogy többet hallgatunk a szívünkre, hogy lelkileg tisztábbak lettünk, hogy többet élünk a jelenben, mint azelőtt. Ez a jelenség is csodálatos állapotokkal fog járni, hiszen képesek leszünk átérezni a reggel hangulatát, a napsütés hangulatát, a párunk lelkét, jobban fogjuk érzékelni a bennünket körülölelő szépségeket stb. Mindez természetesen közelebb fog bennünket vinni a valósághoz, az Istenhez.

Feltehetjük a kérdést, hogy mi van akkor, ha az, aki megkapta az átkódolást, utólag mégsem akar megváltozni? Természetesen ebben az esetben az illető személy nagymértékben le fogja csökkenteni az átalakulás folyamatát, ám tapasztalataink szerint nem fogja tudni teljesen leállítani. Az átkódolás egyik csodálatos tulajdonsága pontosan az, hogy, ha egyszer részesültünk benne, akkor nincs visszaút. Több esetben is megtörtént, hogy olyan személyek, akik megkapták az átkódolást, utólag mégsem akartak megváltozni. Ekkor olyan kényszerhelyzetekbe kerültek, melyek - bár sok szenvedés árán -, de úgyis elvezették őket a jósághoz (néhányan közülük még mindig a szenvedés fázisában vannak). Sok egoista ember esetében felszínre kerültek súlyos jellemhibák, melyeket, meg kell oldjanak. Ellenkező esetben tovább fogják fokozni szenvedéseiket, mindaddig, amíg hajlandóak nem lesznek a valódi változásra. Egy másik jelenség is megfigyelhető volt. Miután lejárt a 4-8 hónap, sok esetben már nem volt megengedve a vétkezés. Ugyanis annak súlyos következményei lettek. Tudnunk kell még azt is, hogy bár az átkódolás segít a rossz szokások megszüntetésében, de azért nekünk is kell törekednünk ezek elhagyására, hiszen a szabad akaratunk révén képesek vagyunk még az átkódolás energiáját is semmibe venni.

Az átkódolás egy másik következménye az, hogy általa egy magas fokú isteni védelemben részesülünk. Ez azt jelenti, hogy, ha balesetünk lenne, vagy ne add Isten, egy háború, akkor mi sokkal nagyobb védettségben fogunk részesülni, mint azok, akik nem kapták meg az átkódolást.

Az átkódolás idővel előhozza a bennünk lappangó problémáinkat. Ez természetes is, hiszen csak úgy lehetünk boldogok, ha megoldjuk elvégzetlen feladatainkat. Ez azt jelenti, hogy az eddig elhalasztott problémáink sorjában felszínre fognak kerülni és végérvényesen meg kell oldanunk azokat. Például, ha még valahol megvolt bennünk a harag természete, akkor lehet, hogy ez jobban meg fog nyilvánulni, mint eddig, ezáltal mi észrevesszük, hogy még bennünk van a harag és alázatosan megpróbálunk majd leszokni róla. Ez a folyamat sokkal könnyebben és sokkal gyorsabban meg fog történni, semmint gondolnánk, hiszen, ebben segít az átkódolás. Ugyanígy, ha például a szervezetünkben elhanyagolt egészségügyi problémák vannak, akkor nagyon valószínű, hogy ezek a betegségek elő fognak bukkanni, hiszen megoldásukkal meg tudunk szabadulni tőlük. Ami viszont lényeges az az, hogy ezeket a betegségeket hamarabb le fogjuk győzni, mint egyébként, hiszen Isten olyan új lehetőségeket fog nekünk felkínálni, melyekkel eddig nem találkoztunk. Lehet, hogy megismerünk egy új gyógynövényt, egy új terápiát. Egy másik érdekes jelenség is meg fog jelenni életünkben. Számos olyan körülmény fog adódni, melyek által eleinte finomabban, később pedig egyre erőteljesebben kényszerítve leszünk arra, hogy megszabaduljunk a rossz szokásainktól. Természetesen, amikor ezek a problémák elő fognak jönni, akkor nem fogjuk magunkat jól érezni, ám akkor gondoljunk arra, hogy ezek a dolgok azért jelentek meg az életünkben, mert véglegesen meg kell szabadulnunk tőlük. Ekkor jusson eszünkbe, hogy ezek a folyamatok az Isteni Szeretet bizonyítékai, hiszen általuk egyértelművé válik számunkra az a tény, hogy Isten személyesen törődik velünk. Istennek is és nekünk is szükségünk van arra, hogy a bennünk levő problémákat megoldjuk, hiszen csak a megtisztulásunk után leszünk képesek arra, hogy elindulhassunk a számunkra kijelölt úton és csak tiszta lélekkel leszünk képesek arra, hogy elérjük a boldogságok világát. Ugyanakkor volt olyan eset is, amikor valakiben már régóta felébredt a megjavulás utáni vágy, ebben az esetben sorozatosan az volt megfigyelhető, hogy egy-két apró problémát leszámítva számos esetben, szinte magától oldódtak meg az illető ember gondjai. Nagyon fontos megjegyeznem, hogy amikor a megtisztulás folyamata elindul, akkor engednünk kell ezeket a folyamatokat megtörténni, vagyis szedjük össze magunkat és akarjuk mi is, hogy megváltozzunk, különben a kényszerítő körülmények fognak bennünket jobb belátásra bírni. A lényeg az, hogy az átkódolás után ki hamarabb, ki később, de meg fog szabadulni hibáitól, ami hosszú távon azt jelenti, hogy kevesebbet fog szenvedni és boldogabb lesz, mint, hogyha nem kapta volna meg az átkódolást. Vegyünk egy példát. Lehet, hogy most 40 évesek vagyunk és időnként fáj a vesénk. Nem igazán törődünk vele. Ám az átkódolás után egyre jobban erősödni fog e fájdalom, így kényszerítve leszünk arra, hogy orvoshoz forduljunk. Ám Isten, a szeretete által, megismertet minket például egy természetgyógyásszal is, aki nagyszerű termékekkel segíti majd a felépülésünket és a lelki okokra is rávilágít. Így előbb-utóbb teljesen meggyógyulunk. Ám, ha nem kaptuk volna meg az átkódolást, halogattuk volna a kezelést, míg betegségünk annyira előrehaladott fázisba nem került volna, hogy sok szenvedés árán - például veseelégtelenségben - meg nem haltunk volna. Melyik megoldás a jobb? Inkább most szenvedjünk egy keveset és oldjuk meg a testi-lelki problémáinkat, semmint a későbbiekben ezek a lappangó gondok tönkretegyék életünket. Úgyhogy senki se féljen az átkódolás során felszínre kerülő problémáktól, hiszen ezek valójában egész életünket szebbé fogják varázsolni.

Az átkódolásnak van gyógyhatása is. Lesznek olyan esetek, amikor Isten súlyos betegségeket fog meggyógyítani az átkódolással.

Egy másik fontos jelenség, amely az átkódolással jár, az, hogy pontosan meg fogjuk érezni, hogy milyen szinten vagyunk spirituális szempontból. Sokan ugyanis, akik hisznek Istenben, tévesen úgy gondolják, hogy pusztán csak azért, mert hisznek Isten létében és mert különböző spirituális dolgokat végeznek, szellemileg magas szinten vannak. Az átkódolás mindenkinek meg fogja mutatni a reális lelki fejlettségi szintjét, hiszen csak a valódi tulajdonságainkat megélve léphetünk tovább. Ha Marosvásárhelyen vagyunk, akkor nem indulhatunk el Párizsból. Ugyanakkor fel fogjuk ismerni a mások reális spirituális szintjét is, így megszabadulhatunk a róluk alkotott illúzióktól. Tudnunk kell azt, hogy a spiritualitás igazi mércéje nem az, hogy ki mekkora csodára képes, hanem, hogy ki mennyire boldog. Az igazán Istennel élő ember ugyanis általában mindig boldog.

Egyes esetekben előfordulhat az is, hogy amikor megkapjuk az átkódolást, nem igazán érzünk semmit és utána sem érezzük a változást. Türelem. Az ilyen esetekben is garantáltan elindulnak a változás folyamatai, csak lehet, hogy mélyebb szinten kezdődnek el és a megnyilvánulásig még hosszabb időnek kell eltelnie. Az is lehet, hogy olyan jellegű változások következnek be, melyeket nem tartunk jelentősnek vagy melyeket egyáltalán nem értékelünk. Az ilyen esetekben javasolt, hogy többször is adjunk vagy kapjunk átkódolást, hogy hamarabb elérjük az érzékelhetőség szintjét.

Ennyi csodálatos dolog olvasása után sokan nagy csodákat fognak elvárni az átkódolástól. Valóban lesz olyan személy, akinél drasztikus és komoly változásokat fog elindítani ez a jelenség. Ám lesz olyan személy is, akinél csalódást fog okozni a kevés, vagy nem olyan jellegű következmény, mint amit elvárt. Ne feledjük el, hogy ebben az esetben a mércét Isten állítja fel, így átalakulásunk annak mértékében fog megtörténni. Ezt természetesen a szabad akaratunk révén felgyorsíthatjuk, vagy lelassíthatjuk. Isten jobban tudja, hogy mire van szükségünk és legyünk nyugodtak, valamint türelmesek, mert a változások előbb-utóbb, igenis, be fognak következni.

Nagyon fontos megjegyeznem, hogy, bár az átkódolás valóban nagyszerű átalakulást eredményezhet, mégsem helyettesíti az eddigi spirituális tevékenységeinket, viszont felerősítheti azok hatásait. Ne essünk tehát abba a tévedésbe, hogy elegendő megkapnunk az átkódolást és ezzel egész életünk lelki fejlődését megoldottuk. Általában pont a fordítottja igaz. Számos ember az átkódolás következtében kezdett el vágyni egy magasabb lelki fejlettségi szint után, melynek hatására különböző - a lelki fejlődést elősegítő - tevékenységekbe kezdett.

A végén még el kell mondanom egy igen fontos dolgot. Mivel az elménk sokszor nem érzékeli az átalakulásokat, ezért végtelenül fontos, hogy havonta, vagy maximum másfél havonta kapjuk meg ismét az átkódolást. Mindezt 5-6 évig folytonosan. Erre azért van szükség, mert így mindig tudatosítani tudjuk, hogy milyen átalakuláson mentünk már át, illetve újból és újból meg tudjuk erősíteni az átkódolás folyamatát.

// Pár hónapon belül el fog készülni egy weboldal is, valószínűleg atkodolas.wikidot.com címmel. Itt majd beszámolókat és egyéb információkat, időnként pedig a kérdéseikre válaszokat is kaphatnak.

Befejezésképpen gondolom, a tisztelt olvasó örül annak, hogy hozzá is eljutott Isten Végtelen Szeretete, melynek segítségével lehetségessé vált a tényleges Isteni Akarathoz való visszatérés. Gondolom az is jó hír, hogy ön innentől kezdve, ha akarja, boldogságban, harmóniában, szeretetben élhet le egy szép életet. Az átkódolás egy hatalmas kincs. Jómagam sok spirituális eszközt ismerek, ám először találkoztam egy olyan lehetőséggel, melynek segítségével Isten hosszú távon el tud vezetni bennünket a boldogsághoz, még akkor is, ha utólag meggondolnánk magunkat. Jó, ha tudja, hogy az Ön átkódolása által hozzájárul a Föld rezonanciájának a megváltoztatásához, amennyiben pedig továbbadja azt, akkor egyenesen Isten Tervének - a Földi és Égi Paradicsom Tervének -- a megvalósulása részesévé válik. Ne feledje el, hogy Istennek szüksége van olyan emberekre, akik tovább terjesztik az Isteni Akaratra való ráhangolódást. Úgy gondolom, hogy az átkódolás segítségével, reális esélyünk van a Föld sorsának a megváltoztatására. Történelmi pillanatok ezek, melyek ismét bizonyítják Isten Végtelen Szeretetét, újbóli "alászállását a Földre". Ezt a hatalmas lehetőséget felhasználhatjuk vagy elpazarolhatjuk. Isten megtette ismét a Maga dolgát, a többi immár rajtunk múlik. Isten adja, hogy mi is akarjuk azt, amit Ő akar, hogy elkerüljük a nehézségeket és, hogy boldogságban éljünk az idők végezetéig!

== Összefoglaló

. Az Univerzumot egy Szerető Tudat irányítja, melyet Istennek nevezünk.
. 2008. Január 19-én Isten megadta az emberiségnek az *Átkódolást*. Azért adta meg, hogy általa megszabadulhassunk az egyre súlyosabb helyzetektől. Az átkódolás azt jelenti, hogy Isten, végtelen képességei által, visszavezet az Eredeti Isteni Tervhez.
. Isten szeret bennünket és azt akarja, hogy a belső, mély, főleg lelki vágyainkat teljesítse. A belső, mély vágyunk azonos az Isteni Akarattal, mely nem más, mint az Isten által számunkra előkészített életút.
. Életutunkat beteljesítve elképzelhetetlenül boldog életünk lesz.
. Minden, ami az Univerzumban létezik, bizonyos frekvencián vibrál. A tudósok kimutatták, hogy hasonló frekvenciák vonzzák, különböző frekvenciák pedig taszítják egymást. Ez a rezonancia törvénye. Az átkódolás energiájának rezgésszáma nagyon magas, tehát így képessé tesz arra, hogy sorsunkba bevonzzuk az Isteni Akarat által előkészített csodálatos életünkhöz vezető eseményeket.
. Az átkódolás nem adható át mindenkinek. Például nem javallott 5 éves kor alatt, testileg legyengült embereknek, bizonyos betegségben szenvedőknek és egyes esetekben öregeknek sem. Ugyanakkor naponta nem ajánlott többször adni, vagy kapni az átkódolást. (a részleteket lásd a megfelelő fejezetnél)
. Az átkódolást csak az adhatja tovább, aki valaki mástól már megkapta. De azután egész életében képes lesz számos ember életét Isten által a jó irányba vezetni.
. Minden esetben, mielőtt átadnánk az átkódolást, kötelező, hogy a jelölt személlyel ismertessük ennek előnyeit és következményeit. Ez azt jelenti, hogy vagy el kell előtte olvasnia az átkódolás leírását, vagy pedig nekünk kell vele részletesen ismertetnünk azt. Kötelező, hogy minden ember csakis és kizárólag szabad akaratából, a következményeket ismerve és felvállalva kaphatja meg az átkódolást! Ellenkező esetben az illető ember beleegyezése nélkül beleavatkozunk az ő szabad akaratába és megváltoztatjuk az életét. Ez ránk nézve is súlyos következményekkel fog járni.
. Mielőtt valakinek átadnánk az átkódolást, kötelező megkérdeznünk, hogy van-e valamilyen betegsége, esetleg testileg gyenge állapotban van-e? Ha igen, az erre vonatkozó részben leírtak szerint kell eljárnunk. Máskülönben árthatunk is az embereknek.
. Ha mindezeket a lépéseket betartottuk, akkor elkezdhetjük az átkódolást. Testtartásunk a megfelelő pozícióban, az erre vonatkozó részben leírtak szerint kell legyen. Magunkban, teljes hittel a következőket mondjuk:
+
[quote]
"Uram Istenem, Égi Atyám, tudom, hogy Te bármire képes vagy. Tudom, hogy, ha akarod, akkor a velem szemben levő Pált (elmondjuk az illető ember keresztnevét) pár percen belül örökre megváltoztathatod. Kérlek, itt és most a végtelen képességeddel kódold át őt. Tudom, hogy amint ezt megteszed, Pál örökre meg fog változni és innentől kezdve más ember lesz az idők végezetéig. Kérlek hát, kódold át őt. Kérlek, ismét tégy csodát, és újra mutasd meg Végtelen Kegyelmedet, kódold át itt és most Pált".

. A szöveg elmondása során egy szentséggel és magasztossággal telt állapotban kell lennünk, éreznünk kell, amint ismét bekövetkezik a csoda, amint újra elkezdődik egy ember életének a megváltozása. Érezni fogjuk, amint jobb kezünkön keresztül az átkódolás energiája átáramlik a jelölt testébe.
. Az átkódolás általában 16 perces kell legyen, kivételt képeznek a gyermekek, betegek, legyengült szervezetűek, esetleg az öregek. (lásd a leírásban az erre vonatkozó részleteket)
. Az átkódolás alatt sokat segíthet, ha egy magasztos zenét hallgatunk. Ajánlatos *Hans Zimmer* a "The DaVinci Code" filmzene albumának a "*Chevaliers de Sangreal*" című számát felhasználni erre az alkalomra.
. Az átkódolás után számos esemény bekövetkezhet, mely az Isteni Akarat fele fogja irányítani életünket. (lásd a leírásban az erre vonatkozó részleteket)
. Az átkódolás után 4-8 hónap szükséges a testünk és a tudatunk alapvető átalakulásához, utána kevésbé lesz megengedve a vétkezés, ám az átkódolás, minden szinten, csak 5-6 év alatt fogja teljesen kifejteni a hatását, mivel Isten fokozatosan alakít át bennünket.
. Az átkódolás után spirituális és profán vágyak fognak bennünk felébredni, valószínűleg olyanok, melyeket eddig nem tudatosítottunk. Igyekezzünk követni ezeket, mert ezek fognak elindítani bennünket az Isteni Akarat beteljesüléséhez.
. Idővel az átkódolás elő fogja hozni a bennünk lappangó testi-lelki problémáinkat. Ezeket meg kell oldanunk, hiszen csak így teljesíthetjük be küldetésünket. A megoldásban Isten sok segítséget fog nyújtani. Rossz szokásainkról is könnyebben leszokhatunk ebben az időben.
. Idővel, kb. 4-8 hónap után, el kell érnünk a melegszívű, jóságos állapotot. Ez bizonyítja majd, hogy az átkódolás valóban változást okozott. Istennek melegszívű, jóságos, nyugodt, lelkiismeretes emberekre van szüksége ahhoz, hogy megváltozzon a társadalmunk. (lásd a leírásban az erre vonatkozó részleteket)
. Az átkódolás hatásait, szabad akaratunk révén, lassíthatjuk vagy gyorsíthatjuk. Jobb alázatosan, a változás szükségességét megérezve engednünk és akarnunk az átalakulás bekövetkeztét, mint, hogy a körülményeink kényszerítsenek rá. Sok más spirituális eszközzel ellentétben, az átkódolás folyamatát nem állíthatjuk le, csak lelassíthatjuk.
. Az átkódolást havonta vagy maximum másfél havonta meg kell ismételnünk 5-6 évig (mindegy, hogy az adás, vagy a fogadás formájában). Ezáltal folyamatosan tudatosíthatjuk a változásokat és elménk nem fogja lelassítani a változások folyamatát.
. Egyéb részleteket a leírásban megtalál. Ne feledje, hogy az átkódolás révén Isten elvezetheti Önt a Teljes Boldogsághoz, illetve, ha Ön is továbbadja azt, akkor ezáltal hozzájárul a Föld rezonanciájának a megváltoztatásához, a megmentéséhez. Isten adja, hogy az Isteni Akarat a Földünkön is beteljesüljön!

Végül pedig azok számára, akik meg akarják ismerni az életfeladatukat, küldetésüket, el kell mondanom, hogy létezik egy egyszerű módszer, melynek segítségével el lehet érni az úgynevezett lélekébredést és melynek segítségével fel lehet ismerni az életutat. Ezt a módszert füzettechnikának hívják. Részleteket ezzel kapcsolatban a link:{note-hu}[soul-awakening.github.io/fuzet] oldalon találhatnak.

_Köszönöm tanítóimnak, barátaimnak és elsősorban Istennek azt a sok segítséget és munkát, mely elvezetett az átkódolás megvalósulásához, valamint ennek az írásnak a létrejöttéhez._

Isteni szeretettel: +
_{authors}_
